"use client"
import * as React from 'react';
import ResponsiveAppBar from './components/ResponsiveAppBar';

export default function HomeV2() {
  return (
    <main>
      <ResponsiveAppBar />
      <div className="w-full h-full my-10 mx-10">
        <h1 className="font-bold text-xl">Stock App V2</h1>
        <p>Generated by create next app</p>
        
        <div className="mt-8">
          <h2 className="font-semibold text-lg mb-4">Customer Management</h2>
          <ul className="space-y-2">
            <li><a href="/v2/customer" className="text-blue-600 hover:text-blue-800 underline">Customer Management (Single Page)</a></li>
            <li><a href="/v2/customer/list" className="text-blue-600 hover:text-blue-800 underline">Customer Management (Multi Page)</a></li>
          </ul>
        </div>
      </div>
    </main>
  );
}